### ISSUE TITLE
Intermittent test results

### ISSUE THREAD

**Issue by paulbjensen** [anephenix/sarus#110]
**Describe the bug**

Sometimes the tests pass, and sometimes they fail. It is intermittent, so we want to spot why it happens and prevent the issue from occurring.

**To Reproduce**

1. run `npm t`
2. If that passes, run 1 until it fails
3. Once 1 fails, capture the test fails, and do it again until you get a different result (passes), noting which tests fail, and if they are the same tests that fail each time.

**Expected behavior**

Ideally tests pass and pass repeatedly - there isn't an intermittent test failure. I think if you run the tests ~ 15 times and there are no failures, then you can be confident that the intermittent test issue has likely been fixed.

**Comment by paulbjensen** [comment]
After running about 6-7 times, I finally got an intermittent test failure. Stacktrace below:

```
 FAIL  __tests__/index/retryConnectionDelay.test.ts (6.238 s)
  ● retry connection delay › by default › should delay the reconnection attempt by 1 second

    expect(received).toBeGreaterThanOrEqual(expected)

    Expected: >= 1000
    Received:    999

      33 |       });
      34 |       const timeNow: any = new Date();
    > 35 |       expect(timeNow - timeThen).toBeGreaterThanOrEqual(1000);
         |                                  ^
      36 |       expect(timeNow - timeThen).toBeLessThan(3000);
      37 |       return newServer.close();
      38 |     });

      at __tests__/index/retryConnectionDelay.test.ts:35:34
      at step (__tests__/index/retryConnectionDelay.test.ts:33:23)
      at Object.next (__tests__/index/retryConnectionDelay.test.ts:14:53)
      at fulfilled (__tests__/index/retryConnectionDelay.test.ts:5:58)

  ● retry connection delay › by default › when passed as a number › should delay the reconnection attempt by that number

    A mock server is already listening on this url

      40 |     describe("when passed as a number", () => {
      41 |       it("should delay the reconnection attempt by that number", async () => {
    > 42 |         const server = new WS(url);
         |                        ^
      43 |         const sarus = new Sarus({ url, retryConnectionDelay: 500 });
      44 |         await server.connected;
      45 |         server.close();

      at new Server (node_modules/mock-socket/src/server.js:27:13)
      at new WS (node_modules/jest-websocket-mock/lib/jest-websocket-mock.cjs.js:111:19)
      at __tests__/index/retryConnectionDelay.test.ts:42:24
      at step (__tests__/index/retryConnectionDelay.test.ts:33:23)
      at Object.next (__tests__/index/retryConnectionDelay.test.ts:14:53)
      at __tests__/index/retryConnectionDelay.test.ts:8:71
      at Object.<anonymous>.__awaiter (__tests__/index/retryConnectionDelay.test.ts:4:12)
      at Object.<anonymous> (__tests__/index/retryConnectionDelay.test.ts:41:66)

 PASS  __tests__/index/messageQueue.test.ts (10.284 s)
 ```

**Comment by paulbjensen** [comment]
Failed again 2 subsequent times after with the same tests, but then passed.

**Comment by paulbjensen** [comment]
Ran 10 times, no issues, I think therefore that this issue is no longer happening, and will close for now.
